spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:file:./data/docmen;AUTO_SERVER=TRUE
  application:
    name: Docmen
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
    show-sql: true
  banner:
    location: classpath:banner.txt

api:
  server:
    url: http://localhost:8080

springdoc:
  swagger-ui:
      tagsSorter: alpha

application:
  title: Система электронного документооборота
  version: 0.0.1


