spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:file:./data/docmen;AUTO_SERVER=TRUE
  application:
    name: Docmen

api:
  server:
    url: http://localhost:8080